# Gather EC2 facts from remote instance
---
- hosts: local
  connection: local
  gather_facts: False
  roles:
      - gather_aws_instances
  vars:
     ansible_python_interpreter: "{{ ansible_playbook_python }}" 
  vars_files:
    - aws_keys.yml
