---
-   name: Install dependencies
    become: yes
    become_method: sudo
    apt:
        state: present
        pkg: "{{ apt_packages}}"

-   name: Get latest app release
    uri:                                                               
        url: https://api.github.com/repos/andreasarne/redovisnings-sida/releases/latest
        return_content: true                                             
    register: json_reponse 
    delegate_to: 127.0.0.1                                            

-   name: ensure app directory exists
    file:
        path: "/home/{{ server_user }}/{{ item }}"
        state: directory
    with_items:
        -   tmp
        -   app

-   name: Unarchive a file that needs to be downloaded
    unarchive:
        src: "{{ json_reponse.json.tarball_url }}"
        dest: "/home/{{ server_user }}/tmp"
        remote_src: yes
        mode: "755"

-   name: Move app content from tmp to app folder
    command: "find /home/{{ server_user }}/tmp -mindepth 2 -maxdepth 2 -type d,f -print -exec mv {} /home/{{ server_user }}/app/ ;"

-   name: Remove tmp folder
    file:
        path: "/home/{{ server_user }}/tmp"
        state: absent

-   name: Install requirements
    pip:
        requirements: "/home/{{ server_user }}/app/requirements.txt"
        virtualenv: "/home/{{ server_user }}/app/venv"
        virtualenv_command: /usr/bin/python3.5 -m venv

-   name: Set FLASK_APP in .profile
    lineinfile:
        path: "/home/{{ server_user }}/.profile"
        regexp: '^export FLASK_APP'
        line: "export FLASK_APP={{ app_file }}"

-   name: Ensure app .env exist
    file:
        path: "/home/{{ server_user }}/app/.env"
        state: touch

-   name: Generate secret key for Flask
    command: 'python3 -c "import uuid; print(uuid.uuid4().hex)"'
    register: secret_key

-   name: Set FLask env vars
    lineinfile:
        path: "/home/{{ server_user }}/app/.env"
        regexp: '{{ item.regexp }}'
        line: "{{ item.line }}"
    with_items: "{{ flask_env_vars }}"

-   name: Init DB
    shell: "cd app && \
        . venv/bin/activate && \
        flask db init"
    ignore_errors: yes
    register: db_init_status

# - debug: msg="{{db_init_status}}"

-   name: Migrate DB
    shell: "cd app && \
        . venv/bin/activate && \
        flask db migrate"
    ignore_errors: yes
    when: db_init_status
    register: not db_migrate_status.failed|bool

-   name: Upgrade DB
    shell: "cd app && \
        . venv/bin/activate && \
        flask db upgrade"

- name: Create a gunicorn log dir
  become: yes
  become_method: sudo
  file:
    path: /var/log/redovisa
    state: directory
    mode: '0755'
    owner: "{{ server_user }}"

-   name: Copy supervisor.conf
    become: yes
    become_method: sudo
    template:
        src:  supervisor.conf.j2
        dest: /etc/supervisor/conf.d/redovisa.conf
        owner: deploy
        mode: 0755
    notify: restart supervisor