version: 2.1
orbs: 
    snyk: snyk/snyk@0.0.8
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: andreasarne/microblog
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
    deploy:
        environment:
            - ANSIBLE_HOST_KEY_CHECKING: False
        docker:
            - image: circleci/python:3.6
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "requirements/deploy.txt" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-

            - run:
                name: install dependencies
                command: |
                    python3 -m venv .venv
                    . .venv/bin/activate
                    pip3 install -r requirements/deploy.txt ansible[azure]
            - save_cache:
                paths:
                  - ./.venv
                key: v1-dependencies-{{ checksum "requirements/deploy.txt" }}
            - run: echo "source ~/repo/.venv/bin/activate" >> $BASH_ENV
    
            - run: echo "$ANSIBLE_VAULT_PASS" > ansible/.vault_pass.txt
            - run: cd ansible/ && ansible-playbook -vvv gather_az_instances.yml --vault-password-file .vault_pass.txt


workflows:
    version: 2.1
    build-and-test:
        jobs:
            - deploy