---
server_user: "deploy"
server_user_pass: "$6$A.n0n6Vs0NWqF$HuwgSU.AOwzP15r8Amj9R5ztmVnoRymtC2HwYBuh0iAo3GqqzYLTJVvdSRndYrRbRjiTIjLeMnJX4ouZGZKJQ1"
server_user_groups:
    -   sudo

db_root_password: "secret_root"
db_user: "app"
db_user_password: "pass"
db_name: "appDB"
ansible_python_interpreter: "python3"

admin_email: andreas_a@outlook.com

docker_username: "andreasarne"
docker_password: "D3tta4rDocker93"



region: northeurope
resource_group: BTH-kmom01-aar-e20886 # Change me
domain_name: arnesson.dev # Change me

root_user: azureuser

vmtags:
    StudentId: "aar" # Change me


local_ssh_location: '/home/zeldah/.ssh/azureci.pub' # Change me

### behövs

root_password: "$6$x.yiGDA57.$.V5yNBOFbAJ9vKJhFhaozAEC62G1a/NIlqgd0SVtYBsow/P0oIQ6gUsyhyvImk..H5PTcoOHbjW7TNp.oOU6O1"

