FROM python:3.5-alpine

RUN adduser -D deploy

WORKDIR /home/deploy

COPY requirements .

RUN python -m venv venv
RUN venv/bin/pip install -r requirements/dev.txt
RUN venv/bin/pip install gunicorn pymysql

COPY app app
COPY migrations migrations
COPY microblog.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP microblog.py

RUN chown -R deploy:deploy ./
USER deploy

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
