FROM python:3.6-alpine

# Uncomment to show validation error
# RUN cd /tmp && echo "hello!"

RUN adduser -D deploy

WORKDIR /home/deploy

COPY requirements/prod.txt requirements.txt

RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn==19.9 pymysql

COPY app app
COPY migrations migrations
COPY microblog.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP microblog.py

RUN chown -R deploy:deploy ./
USER deploy

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
