---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: cGFzc3dvcmQ=
  DB_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: bXlzcWwrcHlteXNxbDovL21pY3JvYmxvZzptaWNyb3Bhc3N3QG15c3FsOjMzMDYvbWljcm9ibG9n