---
-   name: Move conf file
    copy:
        src: files/statsd.conf
        dest: /home/{{ server_user }}/statsd.conf
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'

-   name: Pull prom/statsd-exporter
    command: docker pull prom/statsd-exporter

-   name: Run prom container
    command: docker run -dP --net=host \
            --restart=always \
            -v /home/{{ server_user }}/statsd.conf:/statsd/statsd.conf \
            prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"

-   name: "Launch docker container with microblog application"
    docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        restart_policy: "{{ policy }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        env:
          DATABASE_URL: "{{ database_url }}"
        network_mode: host
        recreate: yes

# -   name: Display details about the goss results
#     debug:
#         msg: "{{ database_url }}"