---
-   name: Launch the new EC2 Instance
    ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ aws_session_token }}"
        group: "{{ item.security_group }}"
        instance_type: "{{ item.instance_type }}"
        instance_tags: "{{ item.instance_tags }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        exact_count: "{{item.count}}"
        count_tag: "{{ item.instance_tags }}"
        # state: present
        # instance_ids: "{{ item.instance_ids }}"
    loop: "{{ instances }}"
    register: ec2
# - debug: var=inventory_dir

-   name: add created instance to hosts file
    add_host:
        name: "{{ item.tagged_instances.0.public_ip }}"
        groups: "{{ item.tagged_instances.0.tags.name }}"
        # inventory_dir: '{{ inventory_dir }}'
    with_items: "{{ ec2.results }}"

-   name: Wait for SSH to come up
    wait_for:
        host: "{{ item.tagged_instances.0.public_ip}}"
        port: 22
        state: started
    with_items: "{{ ec2.results}}"
