---
    
- debug: msg="{{ec2_facts}}"

-   name: Launch the new EC2 Instance
    ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ aws_session_token }}"
        group: "{{ item.security_group }}"
        instance_type: "{{ item.instance_type }}"
        instance_tags: "{{ item.instance_tags }}"
        image: "{{ image }}"
        wait: yes
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: 1
        # exact_count: "{{item.count}}"
        # count_tag: "{{ item.instance_tags }}"
        state: present
        # instance_ids: "{{ item.instance_ids }}"
    loop: "{{ instances }}"
    register: ec2

# - debug: msg="{{ec2.results}}"
# - debug: msg="{{ec2.results[0].instances[0].public_ip}}"
# - debug: var="{{ec2.results[0].instances[0].tags.name}}"

-   name: Wait for SSH to come up
    wait_for:
        host: "{{ item.instances.0.public_ip}}"
        port: 22
        state: started
    with_items: "{{ ec2.results}}"
