---
    -   hosts: monitor
        remote_user: "{{ server_user }}"
        become: yes
        become_method: sudo
        roles:
          - setup_docker
          - prometheus_node_exporter
          - prometheus
          - grafana
