# Provision servers on Azure
---
-   hosts: local
    connection: local # Keep ansible from open ssh connection
    gather_facts: False
    no_log: False
    roles:
        -   provision
        -   gather_az_instances
        -   security_groups
