# Terminate ec2 instances
---
- hosts: local
  connection: local
  gather_facts: False
  vars_files:
      - aws_keys.yml
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}" 
    region: us-east-1
  roles:
      - gather_aws_instances
  tasks:
    - name: Terminate EC2 Instance(s)
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ aws_session_token }}"
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
      with_items: "{{ ec2_facts.instances }}"
      when: item.tags.project == "devops"
      register: terminated_instances

    - name: Refresh hosts/inventory to remove old EC2 isntance
      meta: refresh_inventory
